AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: user api
Resources:
 USERV2Table:
   Type: AWS::DynamoDB::Table
   Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "mailid"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "mailid"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "USERV2"
 UserRegistrationLambdaV2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'com.aws.avidfullstack.handler.UserRequestHandler::handleRequest'
      Runtime: java8
      CodeUri: s3://s3file4/UserLambdav2.zip
      Description: user api
      MemorySize: 512
      Timeout: 60
      Role: 'arn:aws:iam::807291993144:role/newuser'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /adduser
            Method: POST